apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpa-api-deployment
  labels:
    app: cpa-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpa-api
  template:
    metadata:
      labels:
        app: cpa-api
    spec:
      containers:
        - name: cpa-api
          image: danielmapar/cpa-api:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: "mongodb.default.svc.cluster.local"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DBNAME
              value: "cpa"
            - name: MONGO_USERNAME
              value: "root"
            - name: MONGO_PASSWORD
              value: "iRhrF6O0vp"
            - name: IN_K8
              value: "True"
            - name: API_PORT
              value: "5000"
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: cpa-api-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: cpa-api
  type: LoadBalancer