apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpa-api-deployment
  labels:
    app: cpa-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cpa-api
  template:
    metadata:
      labels:
        app: cpa-api
    spec:
      containers:
        - name: cpa-api
          image: dmapar/cpa-api
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: "localhost"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DBNAME
              value: "cpa"
            - name: MONGO_USERNAME
              value: "root"
            - name: MONGO_PASSWORD
              value: "root"
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: cpa-api-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: cpa-api
  type: LoadBalancer